BOARD="beagley-ai"
CPUTHREADS="$(nproc)"
BRANCH="vendor"
RELEASE="noble"
BUILD_MINIMAL="yes"
BUILD_DESKTOP="no"
KERNEL_CONFIGURE="no"
INSTALL_HEADERS="yes"
INSTALL_ARMBIAN_FIRMWARE="yes"
KERNEL_BTF="no"
ROOTFS_TYPE="ext4"
COMPRESS_OUTPUTIMAGE="sha,img,xz"
ENABLE_EXTENSIONS="ti-k3-accelerators"
TI_K3_CMA_MBYTES="256"
