BOARD="beagley-ai"
BRANCH="vendor"
RELEASE="noble"
BUILD_MINIMAL="no"
BUILD_DESKTOP="yes"
DESKTOP_ENVIRONMENT="xfce"
DESKTOP_ENVIRONMENT_CONFIG_NAME="config_base"
DESKTOP_TIER="minimal"
KERNEL_CONFIGURE="no"
ENABLE_EXTENSIONS="ti-k3-accelerators waveshare-5dsi"
